### ISSUE TITLE
[Bug] Immortal Enemies

### ISSUE THREAD

**Issue by neutronstars20** [GoldenKittenPlays/GetLootForKills#3]
My brother and I were both confused and surprised that this mod was making certain enemies immortal, We tested it on Hoarding Bugs, Bracken, Eyeless Dogs, Thumper/Crawler, and the Masked. They drop infinite loot that only the host can see, but can't pick up.
The Hoarding bugs still can die, but the rest can't.

**Comment by GoldenKittenPlays** [comment]
was this mod tested on its own or were there more than one mod. I have not heard this issue before and I do not change anything about the enemy ai itself. I just drop an item when an enemy dies. Please give me more information so I can work out a fix. Thanks for your interest in my mod.

**Comment by neutronstars20** [comment]
Could be a mod clashing with it, since we had like 60 mods, but we did the good'ol disable one at a time and for some reason it was this one, I'll try testing again with my brother and I to see if the other mod that was clashing with it updated and fixed it.
The thing we were racking our head around was that fact we didn't have a mod that effected the eyeless dogs, so we were uncertain as to why they were immortal

**Comment by neutronstars20** [comment]
It could also be linked to the item's monster can drop since some were modded to make it more logical
like a glizzy

**Comment by neutronstars20** [comment]
Alright found the issue, it is this mod, and it's if you make a monster drop a body which I believe is a Vanilla item
I had it for Brakken, "Mouth dog", and Masked since I was curious as to how a body could be an item, but it's fixed now, so it was mainly my fault

**Comment by GoldenKittenPlays** [comment]
> Alright found the issue, it is this mod, and it's if you make a monster drop a body which I believe is a Vanilla item I had it for Brakken, "Mouth dog", and Masked since I was curious as to how a body could be an item, but it's fixed now, so it was mainly my fault

I had no idea bodies could be items.  I will fix this issue on my side too thanks for the info

**Comment by krisqaq** [comment]
> 好吧，找到了问题，就是这个模组，如果你让一个怪物掉落一具尸体，我相信这是一个香草物品， 我把它用于布拉肯、“嘴狗”和蒙面，因为我很好奇尸体如何能是一个项目，但现在已经修复了，所以这主要是我的错

Can you tell me which mod it is?

**Comment by GoldenKittenPlays** [comment]
Think it is the sell bodies mod and enemies no longer seem to be immortal from my mod. Fully tested by myself in lan. The values resync up when selling to the company so do not be scared when it does not show the values correctly and it also gives correct exp
