### ISSUE TITLE
[Bug]thumper can not be die by shovel

### ISSUE THREAD

**Issue by krisqaq** [GoldenKittenPlays/GetLootForKills#5]
I dont know why ,my friends and i cant kill the thumper，We hit him more than ten times with a shovel . And can u tell me where can i configure it? I download the mod in r2modman and my English is not very well,thank you!

**Comment by krisqaq** [comment]
The configuration I'm talking about is configuring this mod. I don't know where to configure it.

**Comment by GoldenKittenPlays** [comment]
> The configuration I'm talking about is configuring this mod. I don't know where to configure it.

I do not use r2modman so I could not tell you sorry but it is the same place as other configs. Mine is GoldenKitten.GetLootForKIlls.cfg

**Comment by krisqaq** [comment]
> > 我说的配置就是配置这个mod。我不知道在哪里配置它。
> 
> 我不使用 r2modman，所以我无法告诉你抱歉，但它与其他配置是相同的地方。我的是GoldenKitten.GetLootForKIlls.cfg

But I cant kill the thumper. it is immortal！

**Comment by GoldenKittenPlays** [comment]
> > > 我说的配置就是配置这个mod。我不知道在哪里配置它。
> > 
> > 
> > 我不使用 r2modman，所以我无法告诉你抱歉，但它与其他配置是相同的地方。我的是GoldenKitten.GetLootForKIlls.cfg
> 
> But I cant kill the thumper. it is immortal！

Let me fix that then thank you for letting me know

**Comment by krisqaq** [comment]
> > > > 我说的配置就是配置这个mod。我不知道在哪里配置它。
> > > 
> > > 
> > > 我不使用 r2modman，所以我无法告诉你抱歉，但它与其他配置是相同的位置。我是GoldenKitten.GetLootForKIlls.cfg
> > 
> > 
> > 但我无法杀死重击者。它是不朽的！
> 
> 让我解决这个问题，然后谢谢你告诉我

Did the mod you updated today fix anything?Yesterday I  encountered the same problem that person encountered before, which was that dogs were immoptal and dropped unlimited loot.

**Comment by GoldenKittenPlays** [comment]
> > > > > 我说的配置就是配置这个mod。我不知道在哪里配置它。
> > > > 
> > > > 
> > > > 我不使用 r2modman，所以我无法告诉你抱歉，但它与其他配置是相同的位置。我是GoldenKitten.GetLootForKIlls.cfg
> > > 
> > > 
> > > 但我无法杀死重击者。它是不朽的！
> > 
> > 
> > 让我解决这个问题，然后谢谢你告诉我
> 
> Did the mod you updated today fix anything?Yesterday I encountered the same problem that person encountered before, which was that dogs were immoptal and dropped unlimited loot.

Hmm I have no clue why my mod would cause this but I will have to look more into it. I thought I fixed it with todays update but it is hard to test when I mainly test myself. Will get back to you on this

**Comment by GoldenKittenPlays** [comment]
Fully tested this new update by myself in lan and it seems to work fine. Do not be alarmed by the values not showing correctly for clients the values are correct when selling them.
